### PR TITLE
Add `iproj.json` and `.ibmi.json` schemas

### PR DESCRIPTION
**Pull request by SanjulaGanepola**
### Changes

Code4i will be removing the `iproj.json` schema (https://github.com/halcyon-tech/vscode-ibmi/pull/1383) so it will be added in this extension along with the `.ibmi.json` schema.

### CODE REVIEW

**Comment by SanjulaGanepola** [comment]
@edmundreinhardt I copied over the schemas exactly as they were in our IBM i Developer extension. Just wanted to confirm that I should be removing the `iasp` and `sql` properties right?

**Review by worksofliam — APPROVED** [review]
Looks ok to me. Shall I report back here when the removal PR has been done?

**Review by edmundreinhardt — APPROVED** [review]
Excellent

**Comment by edmundreinhardt** [comment]
> 

Sure, let us know when we can test it with the base schemas removed

**Pull request merged**
