### PR TITLE
Refactor QSYS/IFS tree items and make include paths expandable

### PR DESCRIPTION
**Pull request by SanjulaGanepola**
### Changes
- Refactor code for rendering QSYS objects and IFS files/folders
- Update labels, descriptions, and tooltips
- Make include paths expandable

### CODE REVIEW

**Comment by SanjulaGanepola** [comment]
This PR branches off the changes in PR #14

**Review by worksofliam — CHANGES_REQUESTED** [review]
Looks like we need to first check if the directory is local first.

image

**Review by edmundreinhardt — APPROVED** [review]
LGTM

**Comment by SanjulaGanepola** [comment]
Include paths are checked to exist locally first. Local include paths are not expandable, but have an action to view them in the explorer:

image

**Comment by worksofliam** [comment]
Explorer looks good. Last part is clicking on an IFS streamfile: the path in the URI needs to be from root.

image

**Pull request merged**
