### PR TITLE
Setup docs site

### PR DESCRIPTION
**Pull request by SanjulaGanepola**
### Changes
Initial setup for docs site (using `docsify`). Several pages are marked currently marked as `Work in Progress`. They will be added in future PRs.

Once this PR is merged, I will deploy the docs site to GitHub Pages.

### CODE REVIEW

**Comment by worksofliam** [comment]
@SanjulaGanepola It'd be cool if you added a script like `nom run docs` so we could launch the site locally too.

**Comment by SanjulaGanepola** [comment]
You can view it locally by running `docsify serve docs` and then going to http://localhost:3000

**Comment by SanjulaGanepola** [comment]
Add docs to `.vscodeignore`

**Review by edmundreinhardt — APPROVED** [review]
Nice, just make sure you ignore from vsix

**Pull request merged**
